// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui02.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MainPanal1 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_MainPanal1, 320);
    lv_obj_set_height(ui_MainPanal1, 480);
    lv_obj_set_align(ui_MainPanal1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MainPanal1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MainPanal1, lv_color_hex(0x4EF4E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainPanal1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MainPanal1, lv_color_hex(0x024F49), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MainPanal1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_MainPanal1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_logo1 = lv_img_create(ui_MainPanal1);
    lv_img_set_src(ui_logo1, &ui_img_1661332484);
    lv_obj_set_width(ui_logo1, LV_SIZE_CONTENT);   /// 369
    lv_obj_set_height(ui_logo1, LV_SIZE_CONTENT);    /// 120
    lv_obj_set_x(ui_logo1, -55);
    lv_obj_set_y(ui_logo1, -190);
    lv_obj_set_align(ui_logo1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_logo1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_logo1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_logo1, 125);

    ui_ToogleButton1 = lv_btn_create(ui_MainPanal1);
    lv_obj_set_width(ui_ToogleButton1, 100);
    lv_obj_set_height(ui_ToogleButton1, 50);
    lv_obj_set_x(ui_ToogleButton1, -80);
    lv_obj_set_y(ui_ToogleButton1, 190);
    lv_obj_set_align(ui_ToogleButton1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ToogleButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ToogleButton1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ToogleButton1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ToogleButton1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ToogleImage2 = lv_img_create(ui_ToogleButton1);
    lv_img_set_src(ui_ToogleImage2, &ui_img_87194987);
    lv_obj_set_width(ui_ToogleImage2, LV_SIZE_CONTENT);   /// 512
    lv_obj_set_height(ui_ToogleImage2, LV_SIZE_CONTENT);    /// 512
    lv_obj_set_align(ui_ToogleImage2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ToogleImage2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ToogleImage2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_ToogleImage2, 1800);
    lv_img_set_zoom(ui_ToogleImage2, 50);

    ui_TablePanel2 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_TablePanel2, 300);
    lv_obj_set_height(ui_TablePanel2, 300);
    lv_obj_set_align(ui_TablePanel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TablePanel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TablePanel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TablePanel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TablePanel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TablePanel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image7 = lv_img_create(ui_TablePanel2);
    lv_img_set_src(ui_Image7, &ui_img_greentable5x4_png);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 174
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 75
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image7, 500);
    lv_obj_set_style_blend_mode(ui_Image7, LV_BLEND_MODE_SUBTRACTIVE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Image7, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ToogleButton1, ui_event_ToogleButton1, LV_EVENT_ALL, NULL);

}
