// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquarelineDisplay_Project

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_rootpanal = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_rootpanal, 320);
    lv_obj_set_height(ui_rootpanal, 480);
    lv_obj_set_align(ui_rootpanal, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_rootpanal, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_rootpanal, lv_color_hex(0x050000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rootpanal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_rootpanal, lv_color_hex(0x10E8EE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_rootpanal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_toppanal = lv_obj_create(ui_rootpanal);
    lv_obj_set_height(ui_toppanal, 50);
    lv_obj_set_width(ui_toppanal, lv_pct(80));
    lv_obj_set_x(ui_toppanal, -2);
    lv_obj_set_y(ui_toppanal, -16);
    lv_obj_set_align(ui_toppanal, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_toppanal, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_shadow_color(ui_toppanal, lv_color_hex(0x16D7E0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_toppanal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_toppanal, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_toppanal, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_toppanal, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_toppanal, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_toplabel = lv_label_create(ui_toppanal);
    lv_obj_set_width(ui_toplabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_toplabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_toplabel, -1);
    lv_obj_set_y(ui_toplabel, -2);
    lv_obj_set_align(ui_toplabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_toplabel, "R E A D I N G");
    lv_obj_set_style_text_font(ui_toplabel, &ui_font_dis30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Temppanal = lv_obj_create(ui_Screen1);
    lv_obj_set_height(ui_Temppanal, 221);
    lv_obj_set_width(ui_Temppanal, lv_pct(98));
    lv_obj_set_align(ui_Temppanal, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Temppanal, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Temppanal, lv_color_hex(0x060000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Temppanal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Temppanal, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Temppanal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempbg = lv_img_create(ui_Temppanal);
    lv_img_set_src(ui_tempbg, &ui_img_speedbg_png);
    lv_obj_set_width(ui_tempbg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tempbg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_tempbg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_tempbg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_tempbg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_tempslider = lv_slider_create(ui_tempbg);
    lv_slider_set_range(ui_tempslider, -20, 60);
    lv_slider_set_value(ui_tempslider, 33, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_tempslider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_tempslider, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_tempslider, 311);
    lv_obj_set_height(ui_tempslider, 290);
    lv_obj_set_x(ui_tempslider, 0);
    lv_obj_set_y(ui_tempslider, 1);
    lv_obj_set_align(ui_tempslider, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_tempslider, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_tempslider, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_tempslider, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_tempslider, lv_color_hex(0x10E8EE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_tempslider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_tempslider, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_tempslider, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_tempslider, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_tempslider, &ui_img_speedfg_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_tempslider, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_tempslider, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_tempMinLabel = lv_label_create(ui_Temppanal);
    lv_obj_set_width(ui_tempMinLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tempMinLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tempMinLabel, -13);
    lv_obj_set_y(ui_tempMinLabel, 8);
    lv_obj_set_align(ui_tempMinLabel, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_tempMinLabel, "-33");
    lv_obj_set_style_text_font(ui_tempMinLabel, &ui_font_dis30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempMaxLabel = lv_label_create(ui_Temppanal);
    lv_obj_set_width(ui_tempMaxLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tempMaxLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tempMaxLabel, 8);
    lv_obj_set_y(ui_tempMaxLabel, 15);
    lv_obj_set_align(ui_tempMaxLabel, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_tempMaxLabel, "60");
    lv_obj_set_style_text_font(ui_tempMaxLabel, &ui_font_dis30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel4, 572);
    lv_obj_set_height(ui_Panel4, 565);
    lv_obj_set_x(ui_Panel4, 96);
    lv_obj_set_y(ui_Panel4, 290);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel4, 800, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0x10E8EE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // ui_tempPlacehold = lv_label_create(ui_Screen1);
    // lv_obj_set_width(ui_tempPlacehold, LV_SIZE_CONTENT);   /// 1
    // lv_obj_set_height(ui_tempPlacehold, LV_SIZE_CONTENT);    /// 1
    // lv_obj_set_x(ui_tempPlacehold, -29);
    // lv_obj_set_y(ui_tempPlacehold, 141);
    // lv_obj_set_align(ui_tempPlacehold, LV_ALIGN_CENTER);
    // lv_label_set_text(ui_tempPlacehold, "88");
    // lv_obj_set_style_text_color(ui_tempPlacehold, lv_color_hex(0xADA9A9), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_opa(ui_tempPlacehold, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_font(ui_tempPlacehold, &ui_font_dis70, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempreading = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_tempreading, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tempreading, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tempreading, -27);
    lv_obj_set_y(ui_tempreading, 140);
    lv_obj_set_align(ui_tempreading, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tempreading, "35");
    lv_obj_set_style_text_color(ui_tempreading, lv_color_hex(0xF40808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tempreading, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tempreading, &ui_font_dis70, LV_PART_MAIN | LV_STATE_DEFAULT);

    // ui_unitPlacehold = lv_label_create(ui_Screen1);
    // lv_obj_set_width(ui_unitPlacehold, LV_SIZE_CONTENT);   /// 1
    // lv_obj_set_height(ui_unitPlacehold, LV_SIZE_CONTENT);    /// 1
    // lv_obj_set_x(ui_unitPlacehold, 44);
    // lv_obj_set_y(ui_unitPlacehold, 141);
    // lv_obj_set_align(ui_unitPlacehold, LV_ALIGN_CENTER);
    // lv_label_set_text(ui_unitPlacehold, " O");
    // lv_obj_set_style_text_color(ui_unitPlacehold, lv_color_hex(0xADA9A9), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_opa(ui_unitPlacehold, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_font(ui_unitPlacehold, &ui_font_dis70, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_unitLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_unitLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_unitLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_unitLabel, 48);
    lv_obj_set_y(ui_unitLabel, 141);
    lv_obj_set_align(ui_unitLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_unitLabel, " V");
    lv_obj_set_style_text_color(ui_unitLabel, lv_color_hex(0xF40808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_unitLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_unitLabel, &ui_font_dis70, LV_PART_MAIN | LV_STATE_DEFAULT);

}
